// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlyvz_gmXsdJzOra_-vaQarx41X82q4xc',
    appId: '1:736106406934:web:2c6478897ef2411a944137',
    messagingSenderId: '736106406934',
    projectId: 'myapp-d633d',
    authDomain: 'myapp-d633d.firebaseapp.com',
    storageBucket: 'myapp-d633d.firebasestorage.app',
    measurementId: 'G-6TSND67D4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwo530ZJGe8UElSX5b0EkWzZIBNMXBcVw',
    appId: '1:736106406934:android:c86c6647a09183fa944137',
    messagingSenderId: '736106406934',
    projectId: 'myapp-d633d',
    storageBucket: 'myapp-d633d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU4WV-sEhv23G_xgVcaILsob6rHZ0D2lU',
    appId: '1:736106406934:ios:d0e028a41b5a42a8944137',
    messagingSenderId: '736106406934',
    projectId: 'myapp-d633d',
    storageBucket: 'myapp-d633d.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU4WV-sEhv23G_xgVcaILsob6rHZ0D2lU',
    appId: '1:736106406934:ios:d0e028a41b5a42a8944137',
    messagingSenderId: '736106406934',
    projectId: 'myapp-d633d',
    storageBucket: 'myapp-d633d.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlyvz_gmXsdJzOra_-vaQarx41X82q4xc',
    appId: '1:736106406934:web:dc0812d773f32e76944137',
    messagingSenderId: '736106406934',
    projectId: 'myapp-d633d',
    authDomain: 'myapp-d633d.firebaseapp.com',
    storageBucket: 'myapp-d633d.firebasestorage.app',
    measurementId: 'G-ELJSPQVWJK',
  );
}
